### ISSUE TITLE
Error Installing redisbeat via pip

### ISSUE THREAD

**Issue by ShipraShalini** [yetship/celerybeatredis#1]
```
$ pip install redisbeat
Collecting redisbeat
  Using cached redisbeat-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/qk/1npqk9fd1m146__ylc2c36cc0000gn/T/pip-build-px8vPV/redisbeat/setup.py", line 13, in <module>
        with open(path.join(here, 'README.md'), encoding='utf-8') as f:
      File "/Users/moonlace/PycharmProjects/wolfe/lib/python2.7/codecs.py", line 884, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: '/private/var/folders/qk/1npqk9fd1m146__ylc2c36cc0000gn/T/pip-build-px8vPV/redisbeat/README.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/qk/1npqk9fd1m146__ylc2c36cc0000gn/T/pip-build-px8vPV/redisbeat/
```

**Comment by liuliqiang** [comment]
@ShipraShalini  thanks for your issue and i found it's the problem of setup.py

now i have fix it and maybe you can try again . 

If you have anyt other suggestion ,just take a pull request as you like :blush:....
