### ISSUE TITLE
AttributeError: 'crontab' object has no attribute 'human_seconds'

### ISSUE THREAD

**Issue by leffss** [yetship/celerybeatredis#28]
settings:
```
CELERYBEAT_SCHEDULE = {     # default beat setting is CELERY_BEAT_SCHEDULE
    'task_check_scheduler': {
        'task': 'tasks.tasks.task_check_scheduler',
        'schedule': timedelta(seconds=60),
        "args": (None, 1, 3),
    },
    'task_check_scheduler_cron': {
        'task': 'tasks.tasks.task_check_scheduler',
        'schedule': crontab(minute='*/1', hour='*', day_of_week='*', day_of_month='*', month_of_year='*'),
        "args": (None, 1, 3),
    }
}
```

error:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/python372/lib/python3.7/site-packages/celery/apps/beat.py", line 109, in start_scheduler
    service.start()
  File "/home/python372/lib/python3.7/site-packages/celery/beat.py", line 588, in start
    humanize_seconds(self.scheduler.max_interval))
  File "/home/python372/lib/python3.7/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/home/python372/lib/python3.7/site-packages/celery/beat.py", line 632, in scheduler
    return self.get_scheduler()
  File "/home/python372/lib/python3.7/site-packages/celery/beat.py", line 627, in get_scheduler
    lazy=lazy,
  File "/home/python372/lib/python3.7/site-packages/redisbeat/scheduler.py", line 48, in __init__
    Scheduler.__init__(self, *args, **kwargs)
  File "/home/python372/lib/python3.7/site-packages/celery/beat.py", line 226, in __init__
    self.setup_schedule()
  File "/home/python372/lib/python3.7/site-packages/redisbeat/scheduler.py", line 72, in setup_schedule
    for entry in tasks))
  File "/home/python372/lib/python3.7/site-packages/redisbeat/scheduler.py", line 72, in <genexpr>
    for entry in tasks))
AttributeError: 'crontab' object has no attribute 'human_seconds'
```

should update function `setup_schedule` like this:
```python
    def setup_schedule(self):
        # init entries
        self.merge_inplace(self.app.conf.CELERYBEAT_SCHEDULE)
        tasks = [jsonpickle.decode(entry) for entry in self.rdb.zrange(self.key, 0, -1)]
        # linfo('Current schedule:\n' + '\n'.join(
        #       str('task: ' + entry.task + '; each: ' + entry.schedule.human_seconds)
        #       for entry in tasks))
        for entry in tasks:
            if hasattr(entry.schedule, 'human_seconds'):
                linfo('Current schedule:\n' + str('task: ' + entry.task + '; each: ' + entry.schedule.human_seconds))
            else:
                cron = '{minute} {hour} {day_of_month} {month_of_year} {day_of_week}'.format(
                    minute=entry.schedule._orig_minute,
                    hour=entry.schedule._orig_hour,
                    day_of_month=entry.schedule._orig_day_of_month,
                    month_of_year=entry.schedule._orig_month_of_year,
                    day_of_week=entry.schedule._orig_day_of_week,
                )
                linfo('Current schedule:\n' + str('task: ' + entry.task + '; cron: ' + cron))
```

**Comment by adrienyhuel** [comment]
Hello,

I modified your code this way, and it works : 

```python
def setup_schedule(self):
        # init entries
        self.merge_inplace(self.app.conf.CELERYBEAT_SCHEDULE)
        tasks = [jsonpickle.decode(entry) for entry in self.rdb.zrange(self.key, 0, -1)]
        linfo('Current schedule:\n' + '\n'.join(
              str('task: ' + entry.task + '; each: ' + entry.schedule.human_seconds)
              for entry in tasks))
```
to
```python
def setup_schedule(self):
        # init entries
        self.merge_inplace(self.app.conf.CELERYBEAT_SCHEDULE)
        tasks = [jsonpickle.decode(entry) for entry in self.rdb.zrange(self.key, 0, -1)]
        linfo('Current schedule:\n' + '\n'.join(
              str('task: ' + entry.task + '; each: ' + repr(entry.schedule))
              for entry in tasks))
```
FYI, repr() is implemented for every schedule type in celery.
For exemple, for crontab, it writes : "<crontab: * * * * * (m/h/d/dM/MY)>"

**Comment by liuliqiang** [comment]
@adrienyhuel would you mind make your change to a pr.
I would like to fix it in master version.
